language: php

php:
    - 5.6
    - 7.0
    - 7.1
    - hhvm

branches:
    only: master

install:
    - if [[ $TRAVIS_PHP_VERSION = 7.0 ]]; then printf "\n" | pecl install apcu; fi
    - if [[ $TRAVIS_PHP_VERSION != 'hhvm' ]]; then phpenv config-rm xdebug.ini; fi
    - if [[ $TRAVIS_PHP_VERSION = 'hhvm' ]]; then mkdir -p ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d; fi
    - phpenv config-add docker/php/config/php.ini
    - composer self-update
    - composer install --prefer-source --optimize-autoloader

script:
    - bin/benchmark --iteration 100
    - bin/benchmark --horizontal-complexity 4 --iteration 100
    - bin/benchmark --vertical-complexity 4 --iteration 100
    - bin/benchmark --horizontal-complexity 4 --vertical-complexity 4 --iteration 100
